services:
  - type: web
    name: e-ocr
    env: python
    plan: free
    runtime: python
    pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
