services:
  - type: web
    name: e-ocr
    env: python           # Bu muhim!
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi
    pythonVersion: 3.10   # Aynan bu yerda ishlaydi
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
